groups:
  - name: node-exporter-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage > 90% for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage > 90% for more than 5 minutes."

      - alert: HighDiskUsage
        expr: 100 * (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage on {{ $labels.instance }} {{ $labels.mountpoint }}"
          description: "Disk usage > 90% for 5 minutes."

      - alert: FilesystemReadOnly
        expr: node_filesystem_readonly == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Read-only filesystem on {{ $labels.instance }}"
          description: "Filesystem {{ $labels.device }} mounted on {{ $labels.mountpoint }} is read-only."

      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "No response from {{ $labels.instance }} for over 1 minute."

  - name: postgres-exporter-alerts
    rules:
      - alert: TooManyConnections
        expr: pg_stat_activity_count > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Too many PostgreSQL connections on {{ $labels.instance }}"
          description: "More than 100 active DB connections for 2 minutes."

      - alert: ReplicationLag
        expr: pg_replication_lag > 1000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL replication lag on {{ $labels.instance }}"
          description: "Replication lag > 1MB for more than 2 minutes."

      - alert: DeadlocksDetected
        expr: increase(pg_stat_database_deadlocks[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Deadlocks detected in PostgreSQL"
          description: "At least one deadlock detected in the last 5 minutes."

      - alert: SlowQueries
        expr: rate(pg_stat_activity_max_tx_duration_seconds[5m]) > 30
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Slow queries in PostgreSQL on {{ $labels.instance }}"
          description: "Transactions exceeding 30s average duration."

      - alert: DatabaseDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL database is down on {{ $labels.instance }}"
          description: "No response from PostgreSQL exporter."

