global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'django-app'
    static_configs:
      - targets: ['volunteer:8000']
        labels:
          group: 'server'
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   metric_relabel_configs:
  #     - source_labels: [id]
  #       target_label: container
  #     - source_labels: [name]
  #       target_label: service
  #     - source_labels: [image]
  #       target_label: image
