global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'volunteer'
    static_configs:
      - targets: ['volunteer:8000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   metric_relabel_configs:
  #     - source_labels: [id]
  #       target_label: container
  #     - source_labels: [name]
  #       target_label: service
  #     - source_labels: [image]
  #       target_label: image
