source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"
gem "csv"
gem "bigdecimal"
gem "base64"
gem "logger"
gem "liquid", "~> 4.0.3"
gem "github-pages", group: :jekyll_plugins
gem "webrick", "~> 1.7"

gem 'jekyll-rtd-theme', '~> 2.0', '>= 2.0.10'

group :jekyll_plugins do
end
